server:
  port: 63000

#Apollo配置
app:
  id: account-service                       #应用ID
apollo:
#  cacheDir: /opt/data/                       #配置本地配置缓存目录
  cluster: default                           #指定使用哪个集群的配置
  meta: http://localhost:8080                #DEV环境配置中心地址
  #meta: http://localhost:8081                #PRO环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: application,micro_service.springboot-common,spring-rocketmq,micro_service.springboot-druid     #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前
